#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell available, use it in
#       place of /bin/sh by altering the first line of this file.
#
#   (2) Avoid modifying this script unless you really know what you are doing. It is
#       provided by Gradle to assist users in trouble. The majority of its code
#       attempts to set up the environment correctly.
#
##############################################################################

# Add default JVM options here.
DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn() {
    echo "$*"
} >&2

die() {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

SCRIPT_DIR=$(cd -- "$(dirname -- "$0")" >/dev/null 2>&1 && pwd)
GRADLE_APP_HOME="$SCRIPT_DIR"

# Extend the path to include the gradle wrapper jar directory
if [ -d "$GRADLE_APP_HOME/gradle/wrapper" ]; then
    CLASSPATH="$GRADLE_APP_HOME/gradle/wrapper/gradle-wrapper.jar:$CLASSPATH"
fi

# Determine JAVA_HOME
if [ -z "$JAVA_HOME" ]; then
    if type java >/dev/null 2>&1; then
        JAVA_HOME=$(dirname "$(dirname "$(command -v java)")")
    elif [ -x /usr/libexec/java_home ]; then
        JAVA_HOME=$(/usr/libexec/java_home)
    else
        JAVA_HOME=/usr
    fi
fi
export JAVA_HOME

# For Cygwin or MSYS, convert paths
if $cygwin || $msys; then
    JAVA_HOME=$(cygpath --windows "$JAVA_HOME")
    CLASSPATH=$(cygpath --path --windows "$CLASSPATH")
    GRADLE_APP_HOME=$(cygpath --path --windows "$GRADLE_APP_HOME")
fi

APP_BASE_NAME=$(basename "$0" .sh)
JAVA_CMD="$JAVA_HOME/bin/java"

# Build the command line
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        "-Dorg.gradle.home=$GRADLE_APP_HOME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Use "xargs" to parse quoted args for proper handling
eval "set -- $(printf '%s\n' "$DEFAULT_JVM_OPTS" | xargs) \"\$@\""

exec "$JAVA_CMD" "$@"
